apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotmac-platform.fullname" . }}-backend
  labels:
    {{- include "dotmac-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.service.backendPort }}
  selector:
    app: dotmac-backend
