apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dotmac-platform.fullname" . }}-config
  labels:
    {{- include "dotmac-platform.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.env.environment | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_FORMAT: {{ .Values.env.logFormat | quote }}
  CORS__ORIGINS: {{ .Values.env.corsOrigins | quote }}
  NEXT_PUBLIC_API_BASE_URL: {{ .Values.endpoints.apiBaseUrl | quote }}
  NEXT_PUBLIC_WS_URL: {{ .Values.endpoints.wsUrl | quote }}
  NEXTAUTH_URL: {{ .Values.endpoints.nextAuthUrl | quote }}
